#requires server to be build using Dockerfile.alpine
#docker build -t gorestserver -f Dockerfile.alpine_bare .
#docker run --rm -it -p 8080:8080  gorestserver

#FROM busybox:musl
#FROM busybox:latest
FROM busybox:glibc
COPY server /server
ENTRYPOINT ["/server"]

EXPOSE 8080	