#requires server to be build using Dockerfile.alpine
#docker build -t gorestserver -f Dockerfile.alpine_bare .
#docker run --rm -it -p 8080:8080  gorestserver

FROM gliderlabs/alpine:3.4
COPY server /bin
ENTRYPOINT ["/bin/server"]
EXPOSE 8080	